services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "HGdb"
      MYSQL_ROOT_PASSWORD: "superserveur"
    ports:
      - "3306:3306" 
    volumes:
      - ./db:/docker-entrypoint-initdb.d  
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      timeout: 20s
      retries: 10

  backjs:
    build: 
      context:
        "./node"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy